name: Generate Prompts

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate-prompts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run prompt generator
        run: |
          bundle exec ruby scripts/generate_prompts.rb

      - name: Archive generated prompts
        run: |
          zip -r prompts_output.zip prompts_output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prompts_output
          path: prompts_output.zip
